/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ctrArchivo;
import Controlador.ctrGramatica;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author carolina
 */
public class GramaticaMf extends javax.swing.JFrame {

    ctrArchivo ctrA= new ctrArchivo();
    ctrGramatica ctr= ctrGramatica.getCtr();
    String path;
    String[][] gra;


    /**
     * Creates new form GramaticaMf
     */
    public GramaticaMf() {
        initComponents();
        txtNumP.setVisible(false);
        btnExaminar.setVisible(false);
        btnIngresoM.setVisible(false);
        btnIngresoF.setVisible(false);
        labelP.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnExaminar = new javax.swing.JButton();
        btnIngresoF = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        FileName = new javax.swing.JLabel();
        btnIngresoM = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        txtNumP = new javax.swing.JTextField();
        labelP = new javax.swing.JLabel();
        labelFileName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnExaminar.setText("Examinar");
        btnExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExaminarActionPerformed(evt);
            }
        });

        btnIngresoF.setText("Ingresar");
        btnIngresoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoFActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setText("GRAMATICA");

        btnIngresoM.setText("Ingresar");
        btnIngresoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoMActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Ingreso por archivo de texto");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Ingresar Manualmente");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        txtNumP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumPActionPerformed(evt);
            }
        });
        txtNumP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumPKeyTyped(evt);
            }
        });

        labelP.setText("Número de producciones:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(jRadioButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnExaminar)
                        .addGap(12, 12, 12)
                        .addComponent(labelFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnIngresoF, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FileName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(labelP)))
                        .addGap(2, 2, 2)
                        .addComponent(txtNumP, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIngresoM, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExaminar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIngresoF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FileName, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(labelP))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIngresoM, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExaminarActionPerformed

         JFileChooser fileChooser=new JFileChooser();
        int opt=fileChooser.showOpenDialog(this);
        if(opt==JFileChooser.APPROVE_OPTION){
            labelFileName.setText(fileChooser.getSelectedFile().getName());
            path=fileChooser.getSelectedFile().getPath();
            
        }



    }//GEN-LAST:event_btnExaminarActionPerformed

    private void btnIngresoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoFActionPerformed
        try {
            // TODO add your handling code here:
            int x=ctrA.tamañoArchivo(path);
            System.out.println(x);
            if(x>0){
                gra=new String[x][2];
                gra=ctrA.procesarArchivo(x,path);

                if(!labelFileName.getText().equals("")){
                    this.setVisible(false);
                }

                ctr.entradasTablaF(x,gra);
                GramaticaIn gramatica = new GramaticaIn();
                gramatica.setVisible(true);
            }else{
                System.out.println(x);
                JOptionPane.showMessageDialog(null, "Archivo vacio");
            }
        } catch (IOException ex) {
            Logger.getLogger(GramaticaMf.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnIngresoFActionPerformed

    private void btnIngresoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoMActionPerformed
        // TODO add your handling code here:
        if(!txtNumP.getText().equals("")){
            this.setVisible(false);
            int x=Integer.parseInt(txtNumP.getText());
            ctr.entradasTablaM(x);
            GramaticaIn gramatica = new GramaticaIn();
            gramatica.manual=true;
            gramatica.setVisible(true);

        }


    }//GEN-LAST:event_btnIngresoMActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
            // TODO add your handling code here:

        if(jRadioButton1.isSelected()){
        btnIngresoM.setVisible(false);
        labelP.setVisible(false);
        txtNumP.setVisible(false);
        labelFileName.setVisible(true);
        btnExaminar.setVisible(true);
        btnIngresoF.setVisible(true);

       }

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        //gramatica.manual=jRadioButton2.isSelected();
         if(jRadioButton2.isSelected()){
         labelFileName.setVisible(false);
        btnIngresoM.setVisible(true);
        labelP.setVisible(true);
        txtNumP.setVisible(true);
        btnExaminar.setVisible(false);
        btnIngresoF.setVisible(false);

       }


    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void txtNumPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumPActionPerformed

    private void txtNumPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumPKeyTyped
        // TODO add your handling code here:
                                                 
        //Se valida que en los txt solo se puedan ingresar numeros.
        char c =evt.getKeyChar();
        if(!Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE){
            evt.consume();
        }
    
    }//GEN-LAST:event_txtNumPKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GramaticaMf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GramaticaMf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GramaticaMf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GramaticaMf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GramaticaMf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FileName;
    private javax.swing.JButton btnExaminar;
    private javax.swing.JButton btnIngresoF;
    private javax.swing.JButton btnIngresoM;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel labelFileName;
    private javax.swing.JLabel labelP;
    private javax.swing.JTextField txtNumP;
    // End of variables declaration//GEN-END:variables
}
